app = "purple-bush-144"

kill_signal = "SIGQUIT"
kill_timeout = 60

[build]
image = "kong/kong-gateway:3.5"

[env]
KONG_CLUSTER_CONTROL_PLANE = "33b21e8d4c.us.cp0.konghq.com:443"
KONG_CLUSTER_SERVER_NAME = "33b21e8d4c.us.cp0.konghq.com"
KONG_CLUSTER_TELEMETRY_ENDPOINT = "33b21e8d4c.us.tp0.konghq.com:443"
KONG_CLUSTER_TELEMETRY_SERVER_NAME = "33b21e8d4c.us.tp0.konghq.com"
KONG_WORKER_PROCESSES = "1"
KONG_MEM_CACHE_SIZE = "64m"
KONG_CLUSTER_MTLS = "pki"
KONG_ROLE = "data_plane"
KONG_KONNECT_MODE = "on"
KONG_VITALS = "off"
KONG_DATABASE = "off"
KONG_STATUS_LISTEN = "0.0.0.0:8010"
KONG_PROXY_ERROR_LOG = "/dev/stderr"

[http_service]
  internal_port = 8000
  force_https = false
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
  [http_service.concurrency]
    type = "requests"
    soft_limit = 10000
    hard_limit = 20000
  [http_service.http_options]
    h2_backend = false

[checks]
  [checks.readiness_probe]
    grace_period = "60s"
    interval = "15s"
    method = "get"
    path = "/status/ready"
    port = 8010
    timeout = "10s"
    type = "http"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 512

[metrics]
port = 8010
path = "/metrics"
