# fly.toml file generated for purple-bush-144 on 2021-08-07T16:23:00-07:00

app = "purple-bush-144"

kill_signal = "SIGINT"
kill_timeout = 5

[env]
  KONG_ROLE = "data_plane"
  KONG_KONNECT_MODE = "on"
  KONG_VITALS = "off"
  KONG_MEM_CACHE_SIZE = "64m"
  KONG_DATABASE = "off"
  KONG_WORKER_PROCESSES = "1"
  KONG_CLUSTER_MTLS = "pki"
  KONG_PROXY_ERROR_LOG="/dev/stderr"
  KONG_ADMIN_ERROR_LOG="/dev/stderr"
  KONG_CLUSTER_CONTROL_PLANE = "33b21e8d4c.us.cp0.konghq.com:443"
  KONG_CLUSTER_SERVER_NAME = "33b21e8d4c.us.cp0.konghq.com"
  KONG_CLUSTER_TELEMETRY_ENDPOINT = "33b21e8d4c.us.tp0.konghq.com:443"
  KONG_CLUSTER_TELEMETRY_SERVER_NAME = "33b21e8d4c.us.tp0.konghq.com"
  KONG_CLUSTER_CERT = "/certs/dp-cert"
  KONG_CLUSTER_CERT_KEY = "/certs/dp-key"
  KONG_LUA_SSL_TRUSTED_CERTIFICATE="system"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8000
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 6
    timeout = "2s"
